/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { FeedbackSubmission } from './types';

export const CATEGORY_TAGS = {
  food: {
    ar: [
      { label: 'طعم لذيذ ✨', type: 'positive' },
      { label: 'كمية كافية 🥘', type: 'positive' },
      { label: 'طازج ومقرمش 🥗', type: 'positive' },
      { label: 'ساخن وجيد 🔥', type: 'positive' },
      { label: 'متأخر في التقديم ⌛', type: 'negative' },
      { label: 'بارد ❄️', type: 'negative' },
      { label: 'ملح زائد 🧂', type: 'negative' },
      { label: 'تحتاج جودة أفضل ⚠️', type: 'negative' }
    ],
    en: [
      { label: 'Delicious Taste ✨', type: 'positive' },
      { label: 'Good Portion 🥘', type: 'positive' },
      { label: 'Fresh & Crisp 🥗', type: 'positive' },
      { label: 'Served Hot 🔥', type: 'positive' },
      { label: 'Late Delivery ⌛', type: 'negative' },
      { label: 'Served Cold ❄️', type: 'negative' },
      { label: 'Too Salty 🧂', type: 'negative' },
      { label: 'Needs Quality Upgrade ⚠️', type: 'negative' }
    ]
  },
  cleaning: {
    ar: [
      { label: 'تنظيف عميق واحترافي ✨', type: 'positive' },
      { label: 'رائحة عطرة ولطيفة 🌸', type: 'positive' },
      { label: 'ترتيب ممتاز للغرفة 🛏️', type: 'positive' },
      { label: 'دقة واهتمام بالتفاصيل 🔍', type: 'positive' },
      { label: 'تأخر عمال النظافة ⌛', type: 'negative' },
      { label: 'زوايا غير نظيفة 🕸️', type: 'negative' },
      { label: 'أرضية مبللة 💦', type: 'negative' },
      { label: 'نقص في المناشف/المستلزمات 🧻', type: 'negative' }
    ],
    en: [
      { label: 'Deep & Pro Clean ✨', type: 'positive' },
      { label: 'Fresh & Pleasant Smell 🌸', type: 'positive' },
      { label: 'Excellent Arrangement 🛏️', type: 'positive' },
      { label: 'Attention to Detail 🔍', type: 'positive' },
      { label: 'Delayed Schedule ⌛', type: 'negative' },
      { label: 'Missed Corners 🕸️', type: 'negative' },
      { label: 'Wet Floor 💦', type: 'negative' },
      { label: 'Missing Towels/Supplies 🧻', type: 'negative' }
    ]
  },
  laundry: {
    ar: [
      { label: 'كيّ وسَحب ممتاز 👔', type: 'positive' },
      { label: 'نظافة فائقة ورائحة منعشة 🌿', type: 'positive' },
      { label: 'كي متقن ومرتب 👌', type: 'positive' },
      { label: 'تسليم سريع في الموعد ⚡', type: 'positive' },
      { label: 'تأخر في إرجاع الملابس ⌛', type: 'negative' },
      { label: 'ملابس غير مكوية جروحاً 💨', type: 'negative' },
      { label: 'تغير أو بهتان اللون 🎨', type: 'negative' },
      { label: 'اختلاط الملابس/مفقودات ⚠️', type: 'negative' }
    ],
    en: [
      { label: 'Excellent Pressing 👔', type: 'positive' },
      { label: 'Super Clean & Fresh Smell 🌿', type: 'positive' },
      { label: 'Perfect Folding 👌', type: 'positive' },
      { label: 'Fast/On-Time Delivery ⚡', type: 'positive' },
      { label: 'Delayed return of clothes ⌛', type: 'negative' },
      { label: 'Poorly Ironed 💨', type: 'negative' },
      { label: 'Color Fading 🎨', type: 'negative' },
      { label: 'Mixed items/Missing item ⚠️', type: 'negative' }
    ]
  }
};

export const INITIAL_MOCK_FEEDBACK: FeedbackSubmission[] = [
  {
    id: 'FB-101',
    residentName: 'أحمد القحطاني',
    roomNumber: 'A-12',
    timestamp: '2026-06-13T14:30:00Z',
    category: 'food',
    subCategory: 'lunch',
    rating: 5,
    tags: ['طعم لذيذ ✨', 'كمية كافية 🥘', 'ساخن وجيد 🔥'],
    comment: 'الغداء اليوم كان ممتازاً جداً، الكبسة كانت ساخنة ولذيذة والكمية مشبعة. شكراً لكم.',
    status: 'resolved'
  },
  {
    id: 'FB-102',
    residentName: 'John Doe',
    roomNumber: 'B-04',
    timestamp: '2026-06-13T11:15:00Z',
    category: 'cleaning',
    subCategory: 'deep_cleaning',
    rating: 4,
    tags: ['تنظيف عميق واحترافي ✨', 'رائحة عطرة ولطيفة 🌸', 'ترتيب ممتاز للغرفة 🛏️'],
    comment: 'The deep cleaning team did a fantastic job today. They even sanitized the vents. Great work.',
    status: 'reviewed'
  },
  {
    id: 'FB-103',
    residentName: 'محمد الدوسري',
    roomNumber: 'C-21',
    timestamp: '2026-06-13T09:00:00Z',
    category: 'food',
    subCategory: 'breakfast',
    rating: 2,
    tags: ['بارد ❄️', 'تحتاج جودة أفضل ⚠️'],
    comment: 'البيض والشاي كانا باردين اليوم والخبز جافاً قليلاً. يرجى الانتباه لحرارة الفطور.',
    status: 'pending'
  },
  {
    id: 'FB-104',
    residentName: 'Salem Al-Mansoori',
    roomNumber: 'A-08',
    timestamp: '2026-06-12T18:45:00Z',
    category: 'laundry',
    subCategory: 'general',
    rating: 5,
    tags: ['كيّ وسَحب ممتاز 👔', 'تسليم سريع في الموعد ⚡'],
    comment: 'تم استلام البدلة في وقت قياسي وكيها كان في قمة الروعة والاناقة. شكراً لنظافتكم.',
    status: 'resolved'
  },
  {
    id: 'FB-105',
    residentName: 'خالد العنزي',
    roomNumber: 'E-15',
    timestamp: '2026-06-12T16:20:00Z',
    category: 'cleaning',
    subCategory: 'regular_cleaning',
    rating: 3,
    tags: ['أرضية مبللة 💦', 'تأخر عمال النظافة ⌛'],
    comment: 'عامل النظافة تأخر عن موعده المعتاد، وترك الأرضية مبللة دون وجود لوحة تحذيرية.',
    status: 'reviewed'
  },
  {
    id: 'FB-106',
    residentName: 'عبدالعزيز العتيبي',
    roomNumber: 'B-18',
    timestamp: '2026-06-12T20:30:00Z',
    category: 'food',
    subCategory: 'dinner',
    rating: 4,
    tags: ['طازج ومقرمش 🥗', 'طعم لذيذ ✨'],
    comment: 'العشاء خفيف ولذيذ، الشوربة والسلطة كانتا ممتازتين للغاية.',
    status: 'resolved'
  },
  {
    id: 'FB-107',
    residentName: 'Michael Smith',
    roomNumber: 'D-11',
    timestamp: '2026-06-11T13:10:00Z',
    category: 'laundry',
    subCategory: 'general',
    rating: 1,
    tags: ['تأخر في إرجاع الملابس ⌛', 'ملابس غير مكوية جروحاً 💨'],
    comment: 'My uniforms were returned 2 days late and they were not ironed properly. I have a presentation tomorrow!',
    status: 'pending'
  },
  {
    id: 'FB-108',
    residentName: 'فيصل الحربي',
    roomNumber: 'A-32',
    timestamp: '2026-06-11T10:00:00Z',
    category: 'cleaning',
    subCategory: 'deep_cleaning',
    rating: 5,
    tags: ['تنظيف عميق واحترافي ✨', 'دقة واهتمام بالتفاصيل 🔍', 'رائحة عطرة ولطيفة 🌸'],
    comment: 'خدمة التنظيف العميق رائعة جداً، تم تنظيف كل ركن حتى خلف خزانة الملابس مدهش!',
    status: 'resolved'
  }
];

export const TRANSLATIONS = {
  ar: {
    title: 'منصة تقييمات السكن',
    subtitle: 'صوتكم يهمنا لتحسين جودة الحياة والخدمات في الكامب',
    food: 'الطعام والوجبات',
    cleaning: 'نظافة الغرف',
    laundry: 'الغسيل والكي (اللاوندري)',
    foodDesc: 'تقييم جودة الوجبات المقدمة ومستويات الرضا',
    cleaningDesc: 'تقييم خدمات تنظيف الغرف الدورية والعميقة',
    laundryDesc: 'تقييم خدمة غسيل وكي الملابس وبطانيات الأسرّة',
    language: 'English',
    breakfast: 'الفطور',
    lunch: 'الغداء',
    dinner: 'العشاء',
    regular_cleaning: 'تنظيف دوري (عادي)',
    deep_cleaning: 'تنظيف عميق',
    general: 'عام',
    roomNumber: 'رقم الغرفة',
    residentName: 'الاسم (اختياري)',
    roomPlaceholder: 'مثال: A-12',
    namePlaceholder: 'مثال: أحمد',
    ratingPrompt: 'كيف تقيم الخدمة بشكل عام؟',
    tagsPrompt: 'يرجى اختيار العبارات المناسبة لتقييمك:',
    commentPrompt: 'هل لديك أي ملاحظات أو مقترحات إضافية؟',
    commentPlaceholder: 'اكتب ملاحظاتك هنا بمصداقية...',
    submitBtn: 'إرسال التقييم الآن',
    cancelBtn: 'إلغاء',
    requiredField: 'هذا الحقل مطلوب',
    successTitle: 'تم إرسال تقييمك بنجاح!',
    successSub: 'نشكرك على وقتك الثمين وملاحظاتك التي تساهم في الارتقاء بمستويات جودة السكن دائماً.',
    newFeedbackBtn: 'تقديم تقييم آخر',
    adminPanel: 'لوحة إدارة المقيمين',
    residentPortal: 'بوابة المقيمين',
    statsOverview: 'نظرة عامة على الإحصائيات',
    overallSatisfaction: 'معدل الرضا العام',
    totalFeedback: 'إجمالي التقييمات',
    activeIssues: 'بلاغات قيد الانتظار',
    byCategory: 'معدل الرضا حسب الفئة',
    feedbackLog: 'سجل التقييمات الواردة',
    searchPlaceholder: 'البحث برقم الغرفة أو الاسم أو التعليق...',
    allCategories: 'كل الأقسام',
    allSubcategories: 'كل الأنواع',
    filterByRating: 'كل التقييمات',
    rating1: 'نجمية واحدة',
    rating2: 'نجمتان',
    rating3: '3 نجمات',
    rating4: '4 نجمات',
    rating5: '5 نجمات',
    exportBtn: 'تصدير البيانات لملف Excel/CSV',
    mockDataBtn: 'توليد عينة بيانات عشوائية',
    noFeedbackFound: 'لم يتم العثور على أي تقييمات تطابق خيارات التصفية.',
    categoryLabel: 'القسم الرئيسي',
    subcategoryLabel: 'النوع الفرعي',
    ratingLabel: 'التقييم',
    roomLabel: 'الغرفة',
    commentLabel: 'التعليق والملاحظات',
    tagsLabel: 'الوسوم المحددة',
    statusLabel: 'حالة الطلب',
    pending: 'قيد الانتظار',
    reviewed: 'تمت مراجعته',
    resolved: 'تم حله',
    dateLabel: 'التاريخ',
    averageRating: 'متوسط التقييم',
    veryHappy: 'ممتاز جداً 😍',
    happy: 'مرضي للغاية 🙂',
    neutral: 'مقبول 😐',
    disappointed: 'غير مرضي ☹️',
    angry: 'سيء جداً 😡',
    residentViewDesc: 'قم بتقديم تقييمك لمساعدتنا في تحسين خدماتنا باستمرار.',
    adminViewDesc: 'راقب مستويات الرضا، وحلل البيانات بالتفصيل، وتتبع المشاكل لحلها سريعاً.',
    dashboardLoading: 'جاري تحديث البيانات والرسومات البيانية...',
    footerText: 'بوابة تقييمات سكان الكامب الرسمية © 2026. جميع الحقوق محفوظة.',
    actionHeader: 'الإجراءات',
    markReviewed: 'تحديد كمقروء',
    markResolved: 'تحديد كمحلول',
    deleteBtn: 'حذف',
    backToHome: 'العودة للرئيسية',
    toastSubmitting: 'جاري إرسال التقييم...',
    toastSuccess: 'تم الإرسال بنجاح، شكراً لك!',
    toastFieldsError: 'الرجاء تعبئة رقم الغرفة وتقييم الرضا!',
    addMockSuccesss: 'تم توليد 5 تقييمات إضافية وتحديث الرسوم البيانية بنجاح!'
  },
  en: {
    title: 'Camp Services Feedback',
    subtitle: 'Your opinion matters. Help us perfect your living standards & daily services',
    food: 'Food & Meals',
    cleaning: 'Room Housekeeping',
    laundry: 'Laundry Service',
    foodDesc: 'Rate food taste, portion sizes, temperature, and overall dining quality',
    cleaningDesc: 'Rate room cleanliness, dusting, bedding freshness, response time',
    laundryDesc: 'Rate clothes washing, ironing, folding quality, and pickup/delivery speed',
    language: 'العربية',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    regular_cleaning: 'Regular Cleaning',
    deep_cleaning: 'Deep Cleaning',
    general: 'General',
    roomNumber: 'Room Number',
    residentName: 'Full Name (Optional)',
    roomPlaceholder: 'e.g. A-12',
    namePlaceholder: 'e.g. Ahmad',
    ratingPrompt: 'How do you rate the service overall?',
    tagsPrompt: 'Please select applicable feedback tags:',
    commentPrompt: 'Do you have additional remarks or suggestions?',
    commentPlaceholder: 'Type your honest feedback here...',
    submitBtn: 'Submit Feedback Now',
    cancelBtn: 'Cancel',
    requiredField: 'This field is required',
    successTitle: 'Feedback Submitted Successfully!',
    successSub: 'Thank you for your valuable feedback! This helps us consistently improve the camp experience for all.',
    newFeedbackBtn: 'Submit Another Feedback',
    adminPanel: 'Manager Dashboard',
    residentPortal: 'Resident Portal',
    statsOverview: 'Statistics Overview',
    overallSatisfaction: 'Overall Satisfaction',
    totalFeedback: 'Total Submissions',
    activeIssues: 'Pending Review Code',
    byCategory: 'Satisfaction by Category',
    feedbackLog: 'Submitted Feedback Log',
    searchPlaceholder: 'Search by room number, resident, or comment...',
    allCategories: 'All Departments',
    allSubcategories: 'All Sub-Types',
    filterByRating: 'All Ratings',
    rating1: '1 Star',
    rating2: '2 Stars',
    rating3: '3 Stars',
    rating4: '4 Stars',
    rating5: '5 Stars',
    exportBtn: 'Export to Excel/CSV',
    mockDataBtn: 'Generate Mock Sample Data',
    noFeedbackFound: 'No feedback entries matched your filter selections.',
    categoryLabel: 'Department',
    subcategoryLabel: 'Sub-Category',
    ratingLabel: 'Rating',
    roomLabel: 'Room',
    commentLabel: 'Comments',
    tagsLabel: 'Selected Tags',
    statusLabel: 'Status',
    pending: 'Pending',
    reviewed: 'Reviewed',
    resolved: 'Resolved',
    dateLabel: 'Date',
    averageRating: 'Average Rating',
    veryHappy: 'Excellent 😍',
    happy: 'Good 🙂',
    neutral: 'Neutral 😐',
    disappointed: 'Unsatisfying ☹️',
    angry: 'Unacceptable 😡',
    residentViewDesc: 'Submit your opinion regarding food, room cleaning, and laundry.',
    adminViewDesc: 'Monitor satisfaction rates, perform filters, and track camp service performance.',
    dashboardLoading: 'Updating graphs and analytics...',
    footerText: 'Official Camp Resident Feedback Portal © 2026. All rights reserved.',
    actionHeader: 'Actions',
    markReviewed: 'Mark Reviewed',
    markResolved: 'Mark Resolved',
    deleteBtn: 'Delete',
    backToHome: 'Back to Home',
    toastSubmitting: 'Submitting feedback...',
    toastSuccess: 'Feedback submitted! Thank you.',
    toastFieldsError: 'Please write your Room Number and select a face score!',
    addMockSuccesss: 'Generated 5 realistic feedback submissions!'
  }
};
